# Generated by Django 3.2.2 on 2021-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasePDL1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='decline_reason',
            field=models.CharField(blank=True, choices=[('Несоответствие клиническим критериям', 'Несоответствие клиническим критериям'), ('Нерепрезентативный материал', 'Нерепрезентативный материал'), ('Материал старше 3 лет', 'Материал старше 3 лет'), ('EGFR+ (НМРЛ)', 'EGFR+ (НМРЛ)'), ('Повторное направление', 'Повторное направление'), ('Не предоставлен материал', 'Не предоставлен материал')], max_length=200, null=True, verbose_name='Clinical Interpratation'),
        ),
        migrations.AddField(
            model_name='case',
            name='decline_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
