# Generated by Django 3.2.4 on 2021-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='ST0001_allow',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='ST1010_allow',
            field=models.BooleanField(default=False, help_text='Gives access to ST1010 application.', verbose_name='Application for IHC:ALK cases'),
        ),
    ]
