# Generated by Django 3.2.5 on 2021-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='signature',
            field=models.ImageField(blank=True, default='ServiceUser/Signatures/Polygon.png', null=True, upload_to='ServiceUser/Signatures'),
        ),
    ]
