# Generated by Django 3.2.5 on 2021-08-29 14:58

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_of_dispatch', models.DateField(default=datetime.date.today, null=True)),
                ('date_of_acquisition', models.DateField(default=datetime.date.today, null=True)),
                ('date_of_registration', models.DateField(default=datetime.date.today, null=True)),
                ('personal_number', models.CharField(blank=True, default='Нет данных', max_length=18, null=True, verbose_name='ID')),
                ('block_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Block codes')),
                ('block_count', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Block count')),
                ('slide_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Slide codes')),
                ('slide_count', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Slide count')),
                ('last_name', models.CharField(blank=True, default='Doe', max_length=20, null=True, verbose_name='Last Name')),
                ('first_name', models.CharField(blank=True, default='John', max_length=15, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='Jenks', max_length=15, null=True, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(choices=[('Не указан', 'Не указан'), ('УЗ «Брестский областной онкологический диспансер»', 'УЗ «Брестский областной онкологический диспансер»'), ('УЗ «Гомельский областной клинический онкологический диспансер»', 'УЗ «Гомельский областной клинический онкологический диспансер»'), ('УЗ «Витебский областной клинический онкологический диспансер»', 'УЗ «Витебский областной клинический онкологический диспансер»'), ('УЗ «Могилёвский областной онкологический диспансер»', 'УЗ «Могилёвский областной онкологический диспансер»'), ('УЗ «Гродненский областной онкологический диспансер»', 'УЗ «Гродненский областной онкологический диспансер»'), ('УЗ «Минский городской клинический онкологический диспансер»', 'УЗ «Минский городской клинический онкологический диспансер»'), ('УЗ «Барановичский онкологический диспансер»', 'УЗ «Барановичский онкологический диспансер»'), ('УЗ «Бобруйский межрайонный онкологический диспансер»', 'УЗ «Бобруйский межрайонный онкологический диспансер»'), ('ГУ «РНПЦ онкологии и медицинской радиологии им. Н.Н. Александрова»', 'ГУ «РНПЦ онкологии и медицинской радиологии им. Н.Н. Александрова»')], default='Не указан', max_length=100, null=True, verbose_name='Region')),
                ('diagnosis', models.CharField(blank=True, default='Не указан', max_length=200, null=True, verbose_name='Diagnosis')),
                ('case_sender', models.CharField(blank=True, default='Не указан', max_length=50, null=True, verbose_name='Doctor (Sender)')),
                ('date_of_report', models.DateField(blank=True, null=True)),
                ('cancer_cell_percentage', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cancer Cells %')),
                ('cancer_cell_category', models.CharField(blank=True, choices=[('<1%', '<1%'), ('>1%', '>1%')], max_length=10, null=True, verbose_name='Cancer Cells Category')),
                ('immune_cell_percentage', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Immune Cells %')),
                ('immune_cell_category', models.CharField(blank=True, choices=[('<1%', '<1%'), ('>1%', '>1%')], max_length=10, null=True, verbose_name='Immune Cells Category')),
                ('clinical_interpretation', models.CharField(blank=True, choices=[('Нет заключения', 'Нет заключения'), ('Отказ', 'Отказ'), ('PD-L1 позитивный', 'PD-L1 позитивный'), ('PD-L1 негативный', 'PD-L1 негативный')], default='Нет заключения', max_length=200, null=True, verbose_name='Clinical Interpratation')),
                ('decline_status', models.BooleanField(blank=True, default=False, null=True)),
                ('decline_reason', models.CharField(blank=True, choices=[('Несоответствие клиническим критериям', 'Несоответствие клиническим критериям'), ('Нерепрезентативный материал', 'Нерепрезентативный материал'), ('Материал старше 3 лет', 'Материал старше 3 лет'), ('EGFR+ (НМРЛ)', 'EGFR+ (НМРЛ)'), ('Повторное направление', 'Повторное направление'), ('Не предоставлен материал', 'Не предоставлен материал')], default='', max_length=200, null=True, verbose_name='Decline Reason')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('version', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('version_state', models.CharField(choices=[('In-progress', 'In-progress'), ('Verified', 'Verified'), ('Obsolete', 'Obsolete')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'ST1011 Cases',
                'db_table': 'ST1011 Case',
            },
        ),
        migrations.CreateModel(
            name='CaseArchive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('personal_number', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'ST1011 Case Archives',
                'db_table': 'ST1011 Case Archive',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_delivery', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_delivery', to='ST1011.case')),
            ],
            options={
                'verbose_name_plural': 'ST1011 Case Deliveries',
                'db_table': 'ST1011 Case Delivery',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ST1011_comment_author', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_case', to='ST1011.case')),
            ],
            options={
                'verbose_name_plural': 'ST1011 Comments',
                'db_table': 'ST1011 Comment',
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='ST1011.casearchive'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ST1011_case_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_consultants',
            field=models.ManyToManyField(blank=True, default=[], related_name='CaseConsultantsST1011', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ST1011_case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseEditorST1011', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date updated')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ST1011_case_approvals', to='ST1011.case')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ST1011_case_consultants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ST1011 Case Approvals',
                'db_table': 'ST1011 Case Approval',
                'ordering': ['date_created'],
                'unique_together': {('case', 'consultant')},
            },
        ),
    ]
