# Generated by Django 3.2.4 on 2021-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0003_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'ST1010 Permissions'},
        ),
        migrations.AlterModelTable(
            name='permission',
            table='ST1010 Permission',
        ),
    ]
