# Generated by Django 3.2.4 on 2021-07-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ST1010', '0005_auto_20210705_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ST1010_Permission', to=settings.AUTH_USER_MODEL),
        ),
    ]
