# Generated by Django 3.2.4 on 2021-07-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0006_alter_permission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_clinician',
            new_name='clinician',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='is_consultant',
            new_name='consultant',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='is_guest',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='is_pathologist',
            new_name='pathologist',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='is_registrar',
            new_name='registrar',
        ),
    ]
