# Generated by Django 3.2.4 on 2021-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0011_auto_20210706_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casearchive',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
