# Generated by Django 3.2.4 on 2021-07-05 08:07

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('date_of_registration', models.DateField(default=datetime.date.today, null=True)),
                ('institution_code', models.PositiveIntegerField(blank=True, choices=[(0, 0), (328112, 328112), (328044, 328044), (328043, 328043), (327933, 327933), (327932, 327932)], null=True, verbose_name='Institution code')),
                ('order_number', models.PositiveIntegerField(null=True, verbose_name='Order number')),
                ('block_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), default=list, null=True, size=None, verbose_name='Block codes')),
                ('block_count', models.PositiveIntegerField(default=1, null=True, verbose_name='Block count')),
                ('slide_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Slide codes')),
                ('slide_count', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Slide count')),
                ('diagnosis', models.CharField(blank=True, max_length=500, null=True, verbose_name='Diagnosis')),
                ('case_sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case sender (Doctor)')),
                ('version', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('version_state', models.BooleanField(choices=[(True, 'In-production'), (False, 'Reviewed')], null=True)),
                ('date_of_report', models.DateField(blank=True, null=True)),
                ('microscopic_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Microscopic Description')),
                ('histological_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Histological Description')),
                ('staining_pattern', models.CharField(blank=True, choices=[('Гранулярное цитоплазматическое окрашивание опухолевых клеток высокой интенсивности не определяется', 'Гранулярное цитоплазматическое окрашивание опухолевых клеток высокой интенсивности не определяется'), ('В большинстве опухолевых клеток определяется гранулярное цитоплазматическое окрашивание высокой интенсивности', 'В большинстве опухолевых клеток определяется гранулярное цитоплазматическое окрашивание высокой интенсивности')], max_length=300, null=True, verbose_name='Staining pattern')),
                ('clinical_interpretation', models.CharField(blank=True, choices=[('ALK-Positive', 'ALK Позитивный'), ('ALK-Negative', 'ALK Негативный')], max_length=300, null=True, verbose_name='Clinical Interpretation')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date updated')),
                ('case_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assistant', to=settings.AUTH_USER_MODEL)),
                ('case_consultants', models.ManyToManyField(blank=True, default=[], related_name='CaseConsultantsST0001', to=settings.AUTH_USER_MODEL)),
                ('case_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL)),
                ('case_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseEditorST0001', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ST1010 Cases',
                'db_table': 'ST1010 Case',
                'ordering': ['date_of_registration'],
                'unique_together': {('institution_code', 'order_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_delivery', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_delivery', to='ST1010.case')),
            ],
            options={
                'verbose_name_plural': 'ST1010 Case Deliveries',
                'db_table': 'ST1010 Case Delivery',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_case', to='ST1010.case')),
            ],
            options={
                'verbose_name_plural': 'ST1010 Comments',
                'db_table': 'ST1010 Comment',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date updated')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_approvals', to='ST1010.case')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ST1010 Case Approvals',
                'db_table': 'ST1010 Case Approval',
                'ordering': ['date_created'],
                'unique_together': {('case', 'consultant')},
            },
        ),
    ]
