# Generated by Django 3.2.4 on 2021-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnosis'),
        ),
    ]
