# Generated by Django 3.2.4 on 2021-07-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ST1010', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_consultants',
            field=models.ManyToManyField(blank=True, default=[], related_name='CaseConsultantsST1010', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseEditorST1010', to=settings.AUTH_USER_MODEL),
        ),
    ]
