# Generated by Django 3.2.4 on 2021-07-05 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ST1010', '0002_auto_20210705_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=True, help_text="Designates basic permissions for guests's access.", verbose_name='Guest Status')),
                ('is_registrator', models.BooleanField(default=False, help_text="Designates  permissions for registrator's access.", verbose_name='Registrator Status')),
                ('is_consultant', models.BooleanField(default=False, help_text="Designates permissions for consultant's access.", verbose_name='Consultant Status')),
                ('is_clinician', models.BooleanField(default=False, help_text="Designates permissions for clinician's access.", verbose_name='Clinician Status')),
                ('is_pathologist', models.BooleanField(default=False, help_text="Designates elevated permissions for pathologist's access.", verbose_name='Pathologist Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
