# Generated by Django 3.2.4 on 2021-07-06 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0007_auto_20210705_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='version_state',
            field=models.BooleanField(choices=[(True, 'In-progress'), (False, 'Reported')], null=True),
        ),
        migrations.CreateModel(
            name='CaseArchive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ST1010.case')),
            ],
        ),
    ]
