# Generated by Django 3.2.4 on 2021-07-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0008_auto_20210706_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='version_state',
            field=models.CharField(choices=[('In-progress', 'In-progress'), ('Verified', 'Verified'), ('Obsolete', 'Obsolete')], max_length=20, null=True),
        ),
    ]
