# Generated by Django 3.2.4 on 2021-07-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0009_alter_case_version_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casearchive',
            options={'verbose_name_plural': 'ST1010 Case Archives'},
        ),
        migrations.AlterModelTable(
            name='casearchive',
            table='ST1010 Case Archive',
        ),
    ]
