# Generated by Django 3.2.4 on 2021-07-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0010_auto_20210706_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casearchive',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='archive',
            field=models.ForeignKey(default=233, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='ST1010.casearchive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casearchive',
            name='name',
            field=models.CharField(default=233, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
