# Generated by Django 3.2.4 on 2021-07-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST1010', '0012_alter_casearchive_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='ST1010.casearchive'),
        ),
    ]
