# Generated by Django 3.2.2 on 2021-06-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='region',
        ),
        migrations.AddField(
            model_name='case',
            name='insitution',
            field=models.CharField(blank=True, default='Не указан', max_length=20, null=True, verbose_name='insitution'),
        ),
    ]
