# Generated by Django 3.2.2 on 2021-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0003_auto_20210604_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='institution',
            field=models.CharField(blank=True, choices=[('Не указан', 'Не указан'), ('УЗ «Гомельский областной клинический онкологический диспансер»', 'УЗ «Гомельский областной клинический онкологический диспансер»'), ('УЗ «Витебский областной клинический онкологический диспансер»', 'УЗ «Витебский областной клинический онкологический диспансер»'), ('УЗ «Могилёвский областной онкологический диспансер»', 'УЗ «Могилёвский областной онкологический диспансер»'), ('УЗ «Минский городской клинический онкологический диспансер»', 'УЗ «Минский городской клинический онкологический диспансер»'), ('РНПЦ ОМР им. Н.Н. Александрова', 'РНПЦ ОМР им. Н.Н. Александрова')], default='Не указан', max_length=80, null=True, verbose_name='institution'),
        ),
        migrations.AlterField(
            model_name='case',
            name='personal_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Personal ID'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('personal_number', 'institution')},
        ),
    ]
