# Generated by Django 3.2.2 on 2021-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0005_auto_20210605_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='institution_code',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (328112, 328112), (328044, 328044), (328043, 328043), (327933, 327933), (327932, 327932)], default=0, null=True, verbose_name='Institution code'),
        ),
    ]
