# Generated by Django 3.2.2 on 2021-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0006_alter_case_institution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='clin_interpretation',
            field=models.CharField(blank=True, choices=[('Не указано', 'Не указано'), ('ALK-Positive', 'ALK Позитивный'), ('ALK-Negative', 'ALK Негативный')], default='Не указано', max_length=200, null=True, verbose_name='Clinical Interpratation'),
        ),
    ]
