# Generated by Django 3.2.2 on 2021-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0007_alter_case_clin_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='personal_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Personal ID'),
        ),
    ]
