# Generated by Django 3.2.2 on 2021-06-08 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0009_auto_20210608_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
