# Generated by Django 3.2.2 on 2021-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0010_alter_case_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.CharField(blank=True, default='Не указан', max_length=200, null=True, verbose_name='Diagnosis'),
        ),
    ]
