# Generated by Django 3.2.2 on 2021-06-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0011_alter_case_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_consultants',
            field=models.ManyToManyField(blank=True, default=[], related_name='CaseConsultantST0001', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='user_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseEditorST0001', to=settings.AUTH_USER_MODEL),
        ),
    ]
