# Generated by Django 3.2.2 on 2021-06-14 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0012_auto_20210612_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_consultants',
            field=models.ManyToManyField(blank=True, default=[], related_name='user_consultants', to=settings.AUTH_USER_MODEL),
        ),
    ]
