# Generated by Django 3.2.2 on 2021-06-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0013_alter_case_user_consultants'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='personal_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Designated number'),
        ),
    ]
