# Generated by Django 3.2.2 on 2021-06-20 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0015_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'ST0001 Case Approvals'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['date_of_registration'], 'verbose_name_plural': 'ST0001 Cases'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'ST0001 Comments'},
        ),
        migrations.AddField(
            model_name='approval',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='approval',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='CaseALK.case'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('case', 'consultant')},
        ),
        migrations.AlterModelTable(
            name='approval',
            table='ST0001 Case Approval',
        ),
        migrations.AlterModelTable(
            name='case',
            table='ST0001 Case',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='ST0001 Comment',
        ),
    ]
