# Generated by Django 3.2.2 on 2021-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0016_auto_20210620_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
