# Generated by Django 3.2.2 on 2021-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0017_alter_approval_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
