# Generated by Django 3.2.2 on 2021-06-23 19:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaseALK', '0020_auto_20210621_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='user_editor',
            new_name='case_editor',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='date_of_response',
            new_name='date_of_report',
        ),
        migrations.AddField(
            model_name='case',
            name='block_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), default=list, null=True, size=None, verbose_name='Block codes'),
        ),
        migrations.AddField(
            model_name='case',
            name='block_count',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Block count'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_consultants',
            field=models.ManyToManyField(blank=True, default=[], related_name='CaseConsultantsST0001', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_sender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case sender (Doctor)'),
        ),
        migrations.AddField(
            model_name='case',
            name='clinical_interpretation',
            field=models.CharField(blank=True, choices=[('Не указано', 'Не указано'), ('ALK-Positive', 'ALK Позитивный'), ('ALK-Negative', 'ALK Негативный')], max_length=300, null=True, verbose_name='Clinical Interpretation'),
        ),
        migrations.AddField(
            model_name='case',
            name='conclusion',
            field=models.CharField(blank=True, choices=[('Гранулярность не определяется', 'Гранулярное цитоплазматическое окрашивание опухолевых клеток высокой интенсивности не определяется'), ('Окрашивание высокой интенсивности', 'В большинстве опухолевых клеток определяется гранулярное цитоплазматическое окрашивание высокой интенсивности')], max_length=300, null=True, verbose_name='Conclusion'),
        ),
        migrations.AddField(
            model_name='case',
            name='microscopic_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Microscopic Description'),
        ),
        migrations.AddField(
            model_name='case',
            name='order_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Order number'),
        ),
        migrations.AddField(
            model_name='case',
            name='slide_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Slide codes'),
        ),
        migrations.AddField(
            model_name='case',
            name='slide_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Slide count'),
        ),
        migrations.AddField(
            model_name='case',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='version_state',
            field=models.BooleanField(blank=True, choices=[('Latest', 'Latest'), ('Old', 'Old')], null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_approval', to='CaseALK.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='case',
            name='institution_code',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (328112, 328112), (328044, 328044), (328043, 328043), (327933, 327933), (327932, 327932)], null=True, verbose_name='Institution code'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_case', to='CaseALK.case'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('institution_code', 'order_number', 'version')},
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_delivery', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_delivery', to='CaseALK.case')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='block_amount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_conclusion',
        ),
        migrations.RemoveField(
            model_name='case',
            name='clin_interpretation',
        ),
        migrations.RemoveField(
            model_name='case',
            name='date_of_delivery',
        ),
        migrations.RemoveField(
            model_name='case',
            name='doctor_sender',
        ),
        migrations.RemoveField(
            model_name='case',
            name='micro_desc',
        ),
        migrations.RemoveField(
            model_name='case',
            name='personal_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='slide_amount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='slide_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='user_consultants',
        ),
        migrations.RemoveField(
            model_name='case',
            name='user_creator',
        ),
        migrations.RemoveField(
            model_name='case',
            name='user_transfer',
        ),
    ]
