# Generated by Django 3.2.2 on 2021-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0022_auto_20210624_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='version_state',
            field=models.BooleanField(choices=[(True, 'Latest'), (False, 'Old')], null=True),
        ),
    ]
