# Generated by Django 3.2.4 on 2021-06-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0023_alter_case_version_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_approvals', to='CaseALK.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='clinical_interpretation',
            field=models.CharField(blank=True, choices=[('ALK-Positive', 'ALK Позитивный'), ('ALK-Negative', 'ALK Негативный')], max_length=300, null=True, verbose_name='Clinical Interpretation'),
        ),
    ]
