# Generated by Django 3.2.4 on 2021-06-28 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0024_auto_20210627_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
