# Generated by Django 3.2.4 on 2021-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0025_alter_case_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='version_state',
            field=models.BooleanField(choices=[(True, 'In-production'), (False, 'Reviewed')], null=True),
        ),
    ]
