# Generated by Django 3.2.4 on 2021-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseALK', '0028_alter_case_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='conclusion',
        ),
        migrations.AddField(
            model_name='case',
            name='staining_pattern',
            field=models.CharField(blank=True, choices=[('Гранулярное цитоплазматическое окрашивание опухолевых клеток высокой интенсивности не определяется', 'Гранулярное цитоплазматическое окрашивание опухолевых клеток высокой интенсивности не определяется'), ('В большинстве опухолевых клеток определяется гранулярное цитоплазматическое окрашивание высокой интенсивности', 'В большинстве опухолевых клеток определяется гранулярное цитоплазматическое окрашивание высокой интенсивности')], max_length=300, null=True, verbose_name='Staining pattern'),
        ),
    ]
