# Generated by Django 3.2.5 on 2021-08-29 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Block Code')),
                ('information', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Information')),
            ],
            options={
                'verbose_name_plural': 'Blocks',
                'db_table': 'Block',
            },
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Block Group')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'Block Groups',
                'db_table': 'Block Group',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id_ambulatory', models.CharField(max_length=20, null=True, unique=True, verbose_name='Ambulatory ID')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle name')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='First name')),
                ('address', models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
                'unique_together': {('last_name', 'middle_name', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='SlideGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Slide Group')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('block_group', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.blockgroup', verbose_name='Block Group')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': 'Slide Groups',
                'db_table': 'Slide Group',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Slide Code (New)')),
                ('information', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Information')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('block', models.ManyToManyField(blank=True, max_length=20, to='ST0001.Block', verbose_name='Block Number')),
                ('block_group', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlockGroup', to='ST0001.blockgroup', verbose_name='Block Group')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.patient', verbose_name='Ambulatory ID')),
                ('slide_group', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.slidegroup', verbose_name='Slide Group')),
            ],
            options={
                'verbose_name_plural': 'Slides',
                'db_table': 'Slide',
            },
        ),
        migrations.AddField(
            model_name='blockgroup',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_group',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Block', to='ST0001.blockgroup', verbose_name='Block Group'),
        ),
        migrations.AddField(
            model_name='block',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ST0001.patient', verbose_name='Ambulatory ID'),
        ),
    ]
