# Generated by Django 3.2.5 on 2021-08-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroup',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlockGroup_Patient', to='ST0001.patient', verbose_name='Patient'),
        ),
    ]
