# Generated by Django 3.2.5 on 2021-08-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0002_alter_blockgroup_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blocks_Patient', to='ST0001.patient', verbose_name='Ambulatory ID'),
        ),
    ]
