# Generated by Django 3.2.5 on 2021-09-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0003_alter_block_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='orginization',
            field=models.CharField(max_length=100, null=True, verbose_name='Orginization'),
        ),
        migrations.AlterField(
            model_name='block',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Blocks', to='ST0001.patient', verbose_name='Ambulatory ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_ambulatory',
            field=models.CharField(error_messages={'unique': 'Амбуляторный ID уже существует!'}, max_length=20, null=True, unique=True, verbose_name='Ambulatory ID'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
