# Generated by Django 3.2.5 on 2021-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0004_auto_20210902_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockgroup',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department'),
        ),
    ]
