# Generated by Django 3.2.5 on 2021-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0005_blockgroup_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockgroup',
            name='organ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organ'),
        ),
    ]
