# Generated by Django 3.2.5 on 2021-09-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0006_blockgroup_organ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='patient',
            name='flat',
            field=models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='Flat'),
        ),
        migrations.AddField(
            model_name='patient',
            name='home',
            field=models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, default='Not Defined', max_length=300, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Slides', to='ST0001.patient', verbose_name='Ambulatory ID'),
        ),
    ]
