# Generated by Django 3.2.5 on 2021-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0007_auto_20210907_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Information'),
        ),
    ]
