# Generated by Django 3.2.5 on 2021-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0009_alter_slide_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='block',
            name='orginization',
            field=models.CharField(max_length=100, null=True, verbose_name='Orginization'),
        ),
    ]
