# Generated by Django 3.2.5 on 2021-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0010_auto_20210912_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='slide',
            name='orginization',
            field=models.CharField(max_length=100, null=True, verbose_name='Orginization'),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='orginization',
            field=models.CharField(max_length=100, null=True, verbose_name='Orginization'),
        ),
    ]
