# Generated by Django 3.2.5 on 2021-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0011_auto_20210912_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='organ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organ'),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='organ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organ'),
        ),
    ]
