# Generated by Django 3.2.5 on 2021-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0013_auto_20210913_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
    ]
