# Generated by Django 3.2.5 on 2021-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0014_patient_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Department'),
        ),
    ]
