# Generated by Django 3.2.5 on 2021-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0015_patient_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='block',
            field=models.ManyToManyField(blank=True, max_length=20, related_name='Block_Slide', to='ST0001.Block', verbose_name='Block Number'),
        ),
    ]
