# Generated by Django 3.2.5 on 2021-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0016_alter_slide_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='organ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='block',
            field=models.ManyToManyField(blank=True, max_length=20, related_name='Block_Slides', to='ST0001.Block', verbose_name='Block Number'),
        ),
    ]
