# Generated by Django 3.2.5 on 2021-09-15 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST0001', '0017_auto_20210914_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='block',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='block',
            name='department',
            field=models.CharField(blank=True, default='Not Defined', max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='block',
            name='organ',
            field=models.CharField(blank=True, default='Not Defined', max_length=50, null=True, verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='block',
            name='orginization',
            field=models.CharField(default='Not Defined', max_length=100, null=True, verbose_name='Orginization'),
        ),
    ]
