# Generated by Django 3.2.4 on 2021-07-08 13:13

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now, null=True)),
                ('personal_number', models.CharField(blank=True, default='Нет данных', max_length=10, null=True, unique=True, verbose_name='ID')),
                ('block_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='00000/00', max_length=20), default=list, help_text='Пример заполнения: 00001/00, 00002/00', null=True, size=None, verbose_name='Block №')),
                ('block_amount', models.PositiveIntegerField(default=1, null=True, verbose_name='Blocks')),
                ('slide_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='00000/00', max_length=20), default=list, help_text='Пример заполнения: 00001/00, 00002/00', null=True, size=None, verbose_name='Slide №')),
                ('slide_amount', models.PositiveIntegerField(default=1, null=True, verbose_name='Slides')),
                ('last_name', models.CharField(blank=True, default='Doe', max_length=20, null=True, verbose_name='Last Name')),
                ('first_name', models.CharField(blank=True, default='John', max_length=15, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='Jenks', max_length=15, null=True, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(choices=[('Не указан', 'Не указан'), ('УЗ «Брестский областной онкологический диспансер»', 'УЗ «Брестский областной онкологический диспансер»'), ('УЗ «Гомельский областной клинический онкологический диспансер»', 'УЗ «Гомельский областной клинический онкологический диспансер»'), ('УЗ «Витебский областной клинический онкологический диспансер»', 'УЗ «Витебский областной клинический онкологический диспансер»'), ('УЗ «Могилёвский областной онкологический диспансер»', 'УЗ «Могилёвский областной онкологический диспансер»'), ('УЗ «Гродненский областной онкологический диспансер»', 'УЗ «Гродненский областной онкологический диспансер»'), ('УЗ «Минский городской клинический онкологический диспансер»', 'УЗ «Минский городской клинический онкологический диспансер»'), ('УЗ «Барановичский онкологический диспансер»', 'УЗ «Барановичский онкологический диспансер»'), ('УЗ «Бобруйский межрайонный онкологический диспансер»', 'УЗ «Бобруйский межрайонный онкологический диспансер»')], default='Не указан', max_length=100, null=True, verbose_name='Region')),
                ('diagnosis', models.CharField(blank=True, default='Не указан', max_length=200, null=True, verbose_name='Diagnosis')),
                ('doctor_sender', models.CharField(blank=True, default='Не указан', max_length=50, null=True, verbose_name='Doctor (Sender)')),
                ('date_of_response', models.DateField(blank=True, null=True)),
                ('doctor_reporter', models.CharField(blank=True, choices=[('Не указан', 'Не указан'), ('Давыдов Д.А.', 'Давыдов Д.А.'), ('Киселев П.Г.', 'Киселев П.Г.')], default='Не указан', max_length=20, null=True, verbose_name='Doctor (Reporter)')),
                ('cancer_cell_percentage', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cancer Cells')),
                ('immune_cell_percentage', models.PositiveIntegerField(default=1, null=True, verbose_name='Immune Cells')),
                ('clin_interpretation', models.CharField(blank=True, choices=[('Нет заключения', 'Нет заключения'), ('PD-L1 positive', 'PD-L1 позитивный'), ('PD-L1 negative', 'PD-L1 негативный')], default='Нет заключения', max_length=200, null=True, verbose_name='Clinical Interpratation')),
                ('decline_status', models.BooleanField(default=False, null=True)),
                ('decline_reason', models.CharField(blank=True, choices=[('Несоответствие клиническим критериям', 'Несоответствие клиническим критериям'), ('Нерепрезентативный материал', 'Нерепрезентативный материал'), ('Материал старше 3 лет', 'Материал старше 3 лет'), ('EGFR+ (НМРЛ)', 'EGFR+ (НМРЛ)'), ('Повторное направление', 'Повторное направление'), ('Не предоставлен материал', 'Не предоставлен материал')], max_length=200, null=True, verbose_name='Clinical Interpratation')),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'ST1011 Cases',
                'db_table': 'ST1011 Case',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorsST1011', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='ST1011.case')),
            ],
            options={
                'verbose_name_plural': 'ST1011 Comments',
                'db_table': 'ST1011 Comment',
                'ordering': ['date_updated'],
            },
        ),
    ]
