# Generated by Django 3.2.4 on 2021-07-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210705_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='is_clinician',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='is_consultant',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='is_pathologist',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='is_registrator',
        ),
    ]
