# Generated by Django 3.2.4 on 2021-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210705_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='ST0002_allow',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='ST1011_allow',
            field=models.BooleanField(default=False, help_text='Gives access to ST1011 application.', verbose_name='Application for IHC:PDL1 cases'),
        ),
    ]
